require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PortalBannersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PortalBanner. As you add validations to PortalBanner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PortalBannersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all portal_banners as @portal_banners" do
      portal_banner = PortalBanner.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:portal_banners)).to eq([portal_banner])
    end
  end

  describe "GET #show" do
    it "assigns the requested portal_banner as @portal_banner" do
      portal_banner = PortalBanner.create! valid_attributes
      get :show, {:id => portal_banner.to_param}, valid_session
      expect(assigns(:portal_banner)).to eq(portal_banner)
    end
  end

  describe "GET #new" do
    it "assigns a new portal_banner as @portal_banner" do
      get :new, {}, valid_session
      expect(assigns(:portal_banner)).to be_a_new(PortalBanner)
    end
  end

  describe "GET #edit" do
    it "assigns the requested portal_banner as @portal_banner" do
      portal_banner = PortalBanner.create! valid_attributes
      get :edit, {:id => portal_banner.to_param}, valid_session
      expect(assigns(:portal_banner)).to eq(portal_banner)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PortalBanner" do
        expect {
          post :create, {:portal_banner => valid_attributes}, valid_session
        }.to change(PortalBanner, :count).by(1)
      end

      it "assigns a newly created portal_banner as @portal_banner" do
        post :create, {:portal_banner => valid_attributes}, valid_session
        expect(assigns(:portal_banner)).to be_a(PortalBanner)
        expect(assigns(:portal_banner)).to be_persisted
      end

      it "redirects to the created portal_banner" do
        post :create, {:portal_banner => valid_attributes}, valid_session
        expect(response).to redirect_to(PortalBanner.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved portal_banner as @portal_banner" do
        post :create, {:portal_banner => invalid_attributes}, valid_session
        expect(assigns(:portal_banner)).to be_a_new(PortalBanner)
      end

      it "re-renders the 'new' template" do
        post :create, {:portal_banner => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested portal_banner" do
        portal_banner = PortalBanner.create! valid_attributes
        put :update, {:id => portal_banner.to_param, :portal_banner => new_attributes}, valid_session
        portal_banner.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested portal_banner as @portal_banner" do
        portal_banner = PortalBanner.create! valid_attributes
        put :update, {:id => portal_banner.to_param, :portal_banner => valid_attributes}, valid_session
        expect(assigns(:portal_banner)).to eq(portal_banner)
      end

      it "redirects to the portal_banner" do
        portal_banner = PortalBanner.create! valid_attributes
        put :update, {:id => portal_banner.to_param, :portal_banner => valid_attributes}, valid_session
        expect(response).to redirect_to(portal_banner)
      end
    end

    context "with invalid params" do
      it "assigns the portal_banner as @portal_banner" do
        portal_banner = PortalBanner.create! valid_attributes
        put :update, {:id => portal_banner.to_param, :portal_banner => invalid_attributes}, valid_session
        expect(assigns(:portal_banner)).to eq(portal_banner)
      end

      it "re-renders the 'edit' template" do
        portal_banner = PortalBanner.create! valid_attributes
        put :update, {:id => portal_banner.to_param, :portal_banner => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested portal_banner" do
      portal_banner = PortalBanner.create! valid_attributes
      expect {
        delete :destroy, {:id => portal_banner.to_param}, valid_session
      }.to change(PortalBanner, :count).by(-1)
    end

    it "redirects to the portal_banners list" do
      portal_banner = PortalBanner.create! valid_attributes
      delete :destroy, {:id => portal_banner.to_param}, valid_session
      expect(response).to redirect_to(portal_banners_url)
    end
  end

end
