require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WindowRequestsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # WindowRequest. As you add validations to WindowRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WindowRequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all window_requests as @window_requests" do
      window_request = WindowRequest.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:window_requests)).to eq([window_request])
    end
  end

  describe "GET #show" do
    it "assigns the requested window_request as @window_request" do
      window_request = WindowRequest.create! valid_attributes
      get :show, {:id => window_request.to_param}, valid_session
      expect(assigns(:window_request)).to eq(window_request)
    end
  end

  describe "GET #new" do
    it "assigns a new window_request as @window_request" do
      get :new, {}, valid_session
      expect(assigns(:window_request)).to be_a_new(WindowRequest)
    end
  end

  describe "GET #edit" do
    it "assigns the requested window_request as @window_request" do
      window_request = WindowRequest.create! valid_attributes
      get :edit, {:id => window_request.to_param}, valid_session
      expect(assigns(:window_request)).to eq(window_request)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WindowRequest" do
        expect {
          post :create, {:window_request => valid_attributes}, valid_session
        }.to change(WindowRequest, :count).by(1)
      end

      it "assigns a newly created window_request as @window_request" do
        post :create, {:window_request => valid_attributes}, valid_session
        expect(assigns(:window_request)).to be_a(WindowRequest)
        expect(assigns(:window_request)).to be_persisted
      end

      it "redirects to the created window_request" do
        post :create, {:window_request => valid_attributes}, valid_session
        expect(response).to redirect_to(WindowRequest.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved window_request as @window_request" do
        post :create, {:window_request => invalid_attributes}, valid_session
        expect(assigns(:window_request)).to be_a_new(WindowRequest)
      end

      it "re-renders the 'new' template" do
        post :create, {:window_request => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested window_request" do
        window_request = WindowRequest.create! valid_attributes
        put :update, {:id => window_request.to_param, :window_request => new_attributes}, valid_session
        window_request.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested window_request as @window_request" do
        window_request = WindowRequest.create! valid_attributes
        put :update, {:id => window_request.to_param, :window_request => valid_attributes}, valid_session
        expect(assigns(:window_request)).to eq(window_request)
      end

      it "redirects to the window_request" do
        window_request = WindowRequest.create! valid_attributes
        put :update, {:id => window_request.to_param, :window_request => valid_attributes}, valid_session
        expect(response).to redirect_to(window_request)
      end
    end

    context "with invalid params" do
      it "assigns the window_request as @window_request" do
        window_request = WindowRequest.create! valid_attributes
        put :update, {:id => window_request.to_param, :window_request => invalid_attributes}, valid_session
        expect(assigns(:window_request)).to eq(window_request)
      end

      it "re-renders the 'edit' template" do
        window_request = WindowRequest.create! valid_attributes
        put :update, {:id => window_request.to_param, :window_request => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested window_request" do
      window_request = WindowRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => window_request.to_param}, valid_session
      }.to change(WindowRequest, :count).by(-1)
    end

    it "redirects to the window_requests list" do
      window_request = WindowRequest.create! valid_attributes
      delete :destroy, {:id => window_request.to_param}, valid_session
      expect(response).to redirect_to(window_requests_url)
    end
  end

end
